version: '3'
services:
  frontend:
    build: frontend/
    image: mern-fe:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb+srv://mongo/ndbscase
      NODE_ENV: development
      PORT: 5000
      JWT_SECRET: abc123
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ndbscase:/data/db
volumes:
  ndbscase:
