version: '3'
services:
    image: microservicescaseregistry.azurecr.io/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: microservicescaseregistry.azurecr.io/backend:latest
    ports:
      - "5000:5000"