name: Build and deploy container app to Azure Web App - nttcrashcourse

 

on:
  push:
    branches:
      - main
  workflow_dispatch:

 

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build fe-image
      id: build-fe-image
      run: |
        docker build . --file=frontend/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${{ github.sha }}

    - name: Build be-image
      id: build-be-image
      run: |
        docker build . --file=backend/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}

    # - name: Build and push container image to registry
    #   uses: docker/build-push-action@v3
    #   with:
    #     push: true
    #     tags: nttcrashcourse.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_a6c3c0d359d5486eafc810d411080d5e }}/crashcourse:${{ github.sha }}
    #     file: ./Dockerfile